name:                exercises
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - fmt
  - text
  - random
  - aeson

default-extensions:
  - OverloadedStrings
  - StandaloneKindSignatures
  - DataKinds
  - RankNTypes
  - PolyKinds
  - TypeOperators
  - TypeFamilies

library:
  source-dirs: src

executables:
  exercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercises

tests:
  exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercises
